spring.application.name: sample-spring-modulith
management.tracing.sampling.probability: 1.0
spring:
  docker:
    compose:
      file: ./docker/docker-compose.yml

otel:
  instrumentation:
    micrometer:
      enabled: true
    service:
      name: "sample-spring-modulith"
    exporter:
      zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"
      otlp:
        endpoint: "http://otel-collector:4318"
        logging:
          enabled: true
        metrics:
          enabled: true
        traces:
          enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    metrics:
      distribution:
        percentiles-histogram:
          http.server.requests: true

server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json
  port: 8084
  servlet:
    context-path: /
